#!/bin/bash
set -e

if [ -f "pre_prepare" ]; then
    ./pre_prepare
fi

if [ -d "mbox" ]; then 
	rmdir mbox # delete directory if already exists. fails if not empty.
fi


PWD=`pwd`
hydra_name=`basename $PWD`

mkdir -p ubuntu_mount 
mount -o loop /var/ubuntu-8.04.2-server-i386.iso ubuntu_mount
trap 'umount ubuntu_mount' 0 2 3 6 9 11 13 15 17
debootstrap --arch i386 hardy mbox file://`pwd`/ubuntu_mount
umount ubuntu_mount
rmdir ubuntu_mount

if [ -d ${HYDRA_BASE-"/usr/share/hydrazine/root"} ]; then
    cp -r ${HYDRA_BASE-"/usr/share/hydrazine/root"} mbox
fi

# this makes sure we can set root's .vimrc etc
cp -r root mbox
if [ -d "/var/Downloads" ]; then
    echo "Downloads exists"
else
    mkdir "/var/Downloads"
fi

mkdir -p /etc/schroot/hydrazine

cat <<END >/etc/schroot/hydrazine/${hydra_name}.conf
[${hydra_name}]
description=${hydra_name} created via prepare_mbox
location=`pwd`/mbox
priority=1
users=$SUDO_USER
root-users=$SUDO_USER
root-groups=admin
run-setup-scripts=true
run-exec-scripts=true
type=directory
END

cat /etc/schroot/hydrazine/*.conf > /etc/schroot/schroot.conf

if [ -f "post_prepare" ]; then
    ./post_prepare
fi

echo Setup complete, launching shell.
echo You can do 'sudo schroot -c mbox' to do it later on.
exec schroot -c ${hydra_name} -d /root

